#!/bin/bash

# 查看 interview-start 函数的超时相关日志

echo "🔍 查看 interview-start 函数的超时相关日志"
echo "=========================================="
echo ""

SUPABASE_URL="${SUPABASE_URL:-https://lafpbfjtbupootnpornv.supabase.co}"

echo "📊 日志查看方式："
echo ""
echo "1. 通过 Supabase Dashboard 查看（推荐）："
echo "   https://supabase.com/dashboard/project/lafpbfjtbupootnpornv/logs/edge-functions"
echo "   选择 'interview-start' 函数"
echo ""
echo "2. 查看最近的错误日志："
echo "   在 Dashboard 中搜索关键词："
echo "   - 'timeout'"
echo "   - '[ERROR]'"
echo "   - '[LLM]'"
echo "   - 'AbortError'"
echo ""
echo "3. 查看请求处理时间："
echo "   搜索 '[REQUEST] 请求处理完成' 查看总耗时"
echo "   搜索 '[LLM]' 查看 LLM 调用耗时"
echo "   搜索 '[THEME]' 查看主题检测耗时"
echo "   搜索 '[QUESTION]' 查看问题生成耗时"
echo ""
echo "=========================================="
echo ""
echo "💡 诊断提示："
echo ""
echo "如果看到 'timeout' 或 'AbortError'："
echo "  - LLM API 响应时间超过 25 秒"
echo "  - 检查网络连接或 LLM API 服务状态"
echo ""
echo "如果看到 '[LLM] 请求超时'："
echo "  - 已自动中止超时请求"
echo "  - 系统会回退到关键词匹配方案"
echo ""
echo "如果总耗时超过 60 秒："
echo "  - Supabase Edge Functions 默认超时是 60 秒"
echo "  - 需要优化 LLM 调用或减少调用次数"
echo ""
echo "=========================================="
echo ""
echo "🧪 测试 API 调用："
echo ""
echo "运行以下命令测试 API（会显示响应时间）："
echo ""
echo "export SUPABASE_URL=\"$SUPABASE_URL\""
echo "export SUPABASE_ANON_KEY=\"your-anon-key\""
echo "bash test-conversation-flow.sh"
echo ""

