#!/bin/bash

# 查看最近的 Edge Functions 日志

echo "🔍 查看最近的 Edge Functions 日志"
echo "=========================================="
echo ""

SUPABASE_PROJECT="lafpbfjtbupootnpornv"

echo "📊 日志查看方式："
echo ""
echo "1. 通过 Supabase Dashboard 查看（推荐）："
echo "   https://supabase.com/dashboard/project/$SUPABASE_PROJECT/logs/edge-functions"
echo ""
echo "2. 选择函数查看："
echo "   - interview-start"
echo "   - memoir-generate"
echo ""
echo "3. 搜索关键词："
echo "   - 'timeout'"
echo "   - '[ERROR]'"
echo "   - '[LLM]'"
echo "   - 'AbortError'"
echo "   - '请求处理完成'"
echo ""
echo "=========================================="
echo ""
echo "💡 快速诊断："
echo ""
echo "如果看到 '[LLM] 请求超时'："
echo "  - LLM API 响应时间超过 25 秒"
echo "  - 检查网络连接或 LLM API 服务状态"
echo ""
echo "如果看到 '请求处理完成, 总耗时=...'："
echo "  - 查看总耗时是否超过 60 秒（Supabase 默认超时）"
echo "  - 如果超过，需要优化 LLM 调用"
echo ""
echo "如果看到 '[THEME]' 或 '[QUESTION]'："
echo "  - 查看各个步骤的耗时"
echo "  - 找出最耗时的步骤"
echo ""
echo "=========================================="
echo ""
echo "🔗 直接访问日志："
echo "   https://supabase.com/dashboard/project/$SUPABASE_PROJECT/logs/edge-functions"
echo ""

